// frontend/src/App.tsx
import React, { useEffect } from 'react'

import './App.css'
import { ethers } from 'ethers'
import Button from '@mui/material/Button'
import Stack from '@mui/material/Stack'
import Boxes from './Boxes'
import tokenJSOn from './assets/TokenizedBalout.json'
const tokenAddress = ''
const backendUrl = 'http://localhost:3000'
function App() {
    const [wallet, setWallet] = React.useState<ethers.Wallet | undefined>()
    const [provider, setProvider] = React.useState<ethers.providers.Provider>(
        ethers.getDefaultProvider('goerli')
    )
    const [contract, setContract] = React.useState<
        ethers.Contract | undefined
    >()
    const [ethValues, setEthValues] = React.useState<{
        ethBalance: string | undefined
        tokenBalance: string | undefined
        votePower: string | undefined
    }>({ ethBalance: undefined, tokenBalance: undefined, votePower: undefined })

    useEffect(() => {
        setProvider(ethers.getDefaultProvider('goerli'))
        const tokenContract = new ethers.Contract(
            tokenAddress,
            tokenJSOn.abi,
            wallet
        )
        setContract(tokenContract)
    }, [wallet])

    const createWallet = () => {
        const myWallet = ethers.Wallet.createRandom().connect(provider)
        setWallet(myWallet)
    }

    const updateValues = () => {
        setEthValues({
            ethBalance: 'loading...',
            tokenBalance: 'loading...',
            votePower: 'loading...',
        })
        wallet?.getBalance().then((balance) => {
            const ethBalance = parseFloat(
                ethers.utils.formatEther(balance)
            ).toString()
            let tokenBalance = ''
            let votePower = ''
            if (contract) {
                contract['balanceOf'](wallet?.address).then(
                    (balanceBN: ethers.BigNumberish) => {
                        tokenBalance = parseFloat(
                            ethers.utils.formatEther(balanceBN)
                        ).toString()
                    }
                )
                contract['getVotes'](wallet?.address).then(
                    (votePowerBN: ethers.BigNumberish) => {
                        votePower = parseFloat(
                            ethers.utils.formatEther(votePowerBN)
                        ).toString()
                    }
                )
            }
            console.log(tokenBalance, tokenBalance, votePower)
        })
    }

    const importWallet = (privateKey: string) => {
        // TODO (optional): make this.wallet to be imported from a privateKey
        updateValues()
    }

    const connectBallotContract = (address: string) => {
        // TODO: create ballot contract instance to this address
        // TODO: fetch information of that ballot to be displayed in the page
        // this.ballotContractAddress = address;
    }

    const requestTokensTen = () => {
        // TODO: request 10 tokens to be minted in the backend
        // this.tokenRequestPending = true;
    }
    const requestTokens = (amount: string) => {
        //this.tokenRequestPending = true;
    }

    return (
        <div className="app">
            <header className="App-header">
                <h1>Tokenized Ballot app</h1>
                {wallet ? <p>{`Your wallet address is ${wallet.address}`}</p> : (
            <Stack spacing={2} direction="row">
              <Button variant="contained" color="success" onClick={createWallet}>create wallet</Button>
              <Button variant="contained" color="secondary" disabled>import wallet</Button>
              <Button variant="contained" disabled>connect wallet</Button>
            </Stack>
      )}
                {/* {wallet && <Boxes />} */}
            </header>
        </div>
    )
}

export default App

// frontend/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { ethers } from 'ethers';
import tokenJson from '../assets/MyToken.json'
import ballotJson from '../assets/Ballot.json'
@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    wallet: ethers.Wallet | undefined;
    provider: ethers.providers.Provider;
    tokenContract: ethers.Contract | undefined;
    ballotContract: ethers.Contract | undefined;

    ethBalance: number | string | undefined;
    tokenBalance: number | string | undefined;
    votePower: number | string | undefined;

    ballotVotePower: number | string | undefined;
    ballotWinningProposal: number | string | undefined;
    ballotWinnerName: string | undefined;

    backendUrl: string | undefined;
    tokenContractAddress: string | undefined;
    ballotContractAddress: string | undefined;

    tokenRequestPending: boolean;
    errorMsg: string | undefined;

    constructor(private http: HttpClient) {
        this.provider = ethers.getDefaultProvider('goerli');
        this.tokenContractAddress = '0x6E3Ec7bD445F25Bf7Da411BAdd4Dac56A4E4Eaaf';
        this.tokenRequestPending = false;
    }

    setTokenContract() {
        if (this.tokenContractAddress) {
            this.tokenContract = new ethers.Contract(this.tokenContractAddress, tokenJson.abi, this.wallet);
        }
    }

    connectBallotContract(address: string) {
        this.ballotContractAddress = address;
        this.ballotContract = new ethers.Contract(address, ballotJson.abi, this.wallet);
        console.log(this.ballotContract, 'this.ballotContract ')
        this.updateValues();
    }

    createWallet() {
        this.wallet = ethers.Wallet.createRandom().connect(this.provider);
        if (this.tokenContractAddress) {
            this.setTokenContract();
            this.updateValues();
        }
    }

    updateValues() {
        [this.ethBalance, this.tokenBalance, this.votePower] = [
            'loading...',
            'loading...',
            'loading...'
        ];
        this.wallet?.getBalance().then((balance) => {
            this.ethBalance = parseFloat(ethers.utils.formatEther(balance));
            if (this.tokenContract) {
                this.tokenContract['balanceOf'](this.wallet?.address).then(
                    (balanceBN: ethers.BigNumberish) => {
                        this.tokenBalance = parseFloat(ethers.utils.formatEther(balanceBN));
                    }
                );
                this.tokenContract['getVotes'](this.wallet?.address).then(
                    (votePowerBN: ethers.BigNumberish) => {
                        this.votePower = parseFloat(ethers.utils.formatEther(votePowerBN));
                    }
                );
            }
            if (this.ballotContract) {
                console.log(this.ballotContract)
                this.ballotContract['votePower'](this.wallet?.address).then(
                    (ballotVotePowerBN: ethers.BigNumberish) => {
                        this.ballotVotePower = parseFloat(ethers.utils.formatEther(ballotVotePowerBN));
                    }
                );
                this.ballotContract['winningProposal']().then(
                    (ballotWinningProposal: number) => {
                        this.ballotWinningProposal = ballotWinningProposal;
                    }
                );
                this.ballotContract['winnerName']().then(
                    (ballotWinnerName: string) => {
                        this.ballotWinnerName = ethers.utils.parseBytes32String(ballotWinnerName);
                    }
                );
            }
        });
    }

    importWallet(secret: string, importMethod: string) {
        if (importMethod == 'mnemonic') {
            this.wallet = ethers.Wallet.fromMnemonic(secret ?? "").connect(this.provider);
        } else {
            this.wallet = new ethers.Wallet(secret ?? "").connect(this.provider);
        }
        if (this.wallet.address.length == 42) {
            this.setTokenContract();
            this.updateValues();
        } else {
            alert(this.errorMsg);
        }
    }


    requestTokensTen() {
        this.tokenRequestPending = true;
    }

    requestTokens(amount: string) {
        this.tokenRequestPending = true;
    }

    delegateTokens(to: string) {
        console.log(`you are delegating tokens to ${to}`);
        if (this.tokenContract) {
            this.tokenContract['delegate'](to).then(this.updateValues());
        }
    }

    transferTokens(to: string, amount: number | string) {
        if (this.tokenContract) {
            this.tokenContract['transfer'](to, amount).then(this.updateValues());
        }
    }

    vote(proposal: number | string, amount: number | string) {
        if (this.ballotContract) {
            this.ballotContract['vote'](proposal, amount).then(this.updateValues());
            console.log('voted successfully');
        }
    }

    connectWallet() {
    }

    disconnectWallet() {
        this.wallet = undefined;
    }
}

<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">Tokenized Ballot DApp</h1>

    <div class="col-lg-6 mx-auto">
        <div *ngIf="!wallet" class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <button (click)="createWallet()" type="button" class="btn btn-success btn-lg px-4 gap-3">Create Wallet
            </button>
            <button type="button" class="btn btn-primary btn-lg px-4 gap-3" 
                data-bs-toggle="modal" data-bs-target="#importWallet">
                Import Wallet
            </button>
            <button (click)="connectWallet()" type="button" class="btn btn-danger btn-lg px-4 gap-3" disabled>Connect
                Wallet </button>
        </div>


        <div *ngIf="wallet">
            <div class="card border-0">
                <div class="card-body">
                    <h4 class="card-title">Wallet Address</h4>
                        {{wallet.address}} 
                            <button (click)="disconnectWallet()" type="button" class="btn btn-danger">
                                Disconnect
                            </button>

                </div>
            </div>
            <div class="card border-0">
                <div class="card-body">
                    <h4 class="card-title">Token Contract</h4>
                    <p class="card-text">
                        {{tokenContractAddress}}
                    </p>
                </div>
            </div>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Your ETH Balance</h4>
                        <p class="card-text">
                            {{ethBalance}}
                        </p>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Your token Balance</h4>
                        <p class="card-text">
                            {{tokenBalance}}
                        </p>
                    </div>
                </div>

                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Your Votes:</h4>
                        <p class="card-text">
                            {{votePower}}
                        </p>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-primary btn-lg px-4 m-3 gap-3" 
                data-bs-toggle="modal" data-bs-target="#transferTokens" *ngIf="tokenBalance">
                Transfer Tokens
            </button>
            <button type="button" class="btn btn-primary btn-lg px-4 m-3 gap-3" 
                data-bs-toggle="modal" data-bs-target="#delegateTokens" *ngIf="tokenBalance">
                Self Delegate
            </button>
        </div>
    </div>

    <div *ngIf="wallet" class="container my-4 text-center">
        <div class="row justify-content-center my-4">
            <div class="my-4">
                <div class="container border rounded m-4">
                    <div *ngIf="!ballotContractAddress" class="row m-4">
                        <div class="input-group mb-3">
                            <span class="input-group-text">Address</span>
                            <input #ballotContractAddress type="text" class="form-control"
                                placeholder="Ballot contract address here" value="0xA5a68F4a956D366711321FB3642cF100bD34018C">
                            <button (click)="connectBallotContract(ballotContractAddress.value)"
                                class="btn btn-success input-group-button">Connect</button>
                        </div>
                    </div>

                    <div *ngIf="ballotContractAddress" class="row m-4">
                        <p>Ballot contract address: {{ballotContractAddress}}</p>
                        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title">Voting Power</h4>
                                    <p class="card-text">
                                        {{ballotVotePower}}
                                    </p>
                                </div>
                            </div>
            
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title">Winning Proposal: </h4>
                                    <p class="card-text">
                                        {{ballotWinningProposal}}
                                    </p>
                                </div>
                            </div>
            
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title">Winner Name: </h4>
                                    <p class="card-text">
                                        {{ballotWinnerName}}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <button type="button" class="btn btn-danger btn-lg px-4 m-3 gap-3" 
                        data-bs-toggle="modal" data-bs-target="#vote">
                            Vote
                        </button>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="importWallet" tabindex="-1" aria-labelledby="importWalletLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="importWalletLabel">Wallet Import</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="input-group mt-4">
                    <input #inputMnemonic type="text" class="form-control"
                        placeholder="mnemonic seed phrase">
                    <div class="input-group-append">
                        <button class="btn btn-success" data-bs-dismiss="modal" type="button"
                            (click)="importWallet(inputMnemonic.value, 'mnemonic')">Via Mnemonic</button>
                    </div>
                </div>
                <div class="input-group mt-4">
                    <input #inputPrivateKey type="text" value='' class="form-control" placeholder="private key">
                    <div class="input-group-append">
                        <button class="btn btn-success" data-bs-dismiss="modal" type="button"
                            (click)="importWallet(inputPrivateKey.value, 'privatekey')">Via Private Key</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="transferTokens" tabindex="-1" aria-labelledby="transferTokensLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="transferTokensLabel">Transfer Tokens</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="input-group mt-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text pe-1" >Transfer To</div>
                    </div>
                    <input #inputTransferTo type="text" class="form-control"
                        placeholder="Enter receiver's address">
                </div>
                <div class="input-group mt-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text pe-4 ps-4">Amount </div>
                    </div>
                    <input #inputTransferAmount type="number" min='0' value='' class="form-control" placeholder="Enter amount to Transfer">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" data-bs-dismiss="modal"
                    (click)="transferTokens(inputTransferTo.value, inputTransferAmount.value)">
                    Transfer
                </button>
            </div>
        </div>
    </div>
</div>

<div *ngIf="wallet" class="modal fade" id="delegateTokens" tabindex="-1" aria-labelledby="delegateTokensLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="delegateTokensLabel">Delegate Tokens</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="input-group mt-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text pe-1" >Delegate To</div>
                    </div>
                    <input #inputDelegateTo type="text" class="form-control"
                        value='{{wallet.address}}'
                        placeholder="Enter delegates address" disabled>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" data-bs-dismiss="modal"
                    (click)="delegateTokens(inputDelegateTo.value)">
                    Delegate
                </button>
            </div>
        </div>
    </div>
</div>

<!--- VOTE MODAL --->
<div class="modal fade" id="vote" tabindex="-1" aria-labelledby="voteLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="voteLabel">Vote</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="input-group mt-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text pe-4 ps-4">Proposal </div>
                    </div>
                    <input #inputProposal type="text" min='0' value='' class="form-control" placeholder="Enter proposal index">
                </div>
                <div class="input-group mt-4">
                    <div class="input-group-prepend">
                        <div class="input-group-text pe-4 ps-4">Amount </div>
                    </div>
                    <input #inputVoteAmount type="text" min='0' value='' class="form-control" placeholder="Enter amount to vote">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" data-bs-dismiss="modal"
                    (click)="vote(inputProposal.value, inputVoteAmount.value)">
                    Vote
                </button>
            </div>
        </div>
    </div>
</div>
